### ISSUE TITLE
(Player)TextDrawCreate and (Player)TextDrawSetString lacks tag support.

### ISSUE THREAD

**Issue by Mortyyka** [Zbyss/samp-weapon-config#16]
Since RC1 you no longer have to use ``format()`` when creating or setting a (Player)TextDraw, however it seems like weapon-config does not support this yet.

**Comment by Zbyss** [comment]
Fixed in [master](https://github.com/Zbyss/samp-weapon-config/tree/master) branch (soon to be merged with main repository), make sure you use YSI as it's dependent on y_va.
