### ISSUE TITLE
Console error on open.mp:

### ISSUE THREAD

**Issue by lPauI** [Zbyss/samp-weapon-config#2]
[Warning] Deprecated console variable "lagcompmode", use "lag_compensation" instead.

It's from line 4097 from this weapon-config version.

**Comment by Zbyss** [comment]
Use the version from [`omp` branch](https://github.com/Zbyss/samp-weapon-config/tree/omp), it's corrected there.
https://github.com/Zbyss/samp-weapon-config/blob/05a0a4138e7aa7ffcdea6d700d9db83d3e353396/weapon-config.inc#L4097

**Comment by lPauI** [comment]
D:\chars.ro\RPG GM\compiler\include\weapon-config.inc(1856) : warning 213: tag mismatch: expected tag "bool", but found none ("_") with omp branch and with master branch

**Comment by Zbyss** [comment]
https://github.com/oscar-broman/samp-weapon-config/issues/218#issuecomment-970731769
