### ISSUE TITLE
[OMP-beta8] Class selection

### ISSUE THREAD

**Issue by mixedthoughts** [Zbyss/samp-weapon-config#9]
Going into class selection after dying for the first time. It literally happens always for the first time.

**Comment by Zbyss** [comment]
I can't reproduce it. Please provide some MCVE if it still occurs, also, please check if it happens on SA-MP server (using Pawn.RakNet and the version from https://github.com/oscar-broman/samp-weapon-config).

**Comment by mixedthoughts** [comment]
the fix is TogglePlayerSpectating( playerid, false );  before spawning. can be used after login or after registering.

this can be closed.
